### ISSUE TITLE
Suggustion: a way of adding self-enchantment into the lore

### ISSUE THREAD

**Issue by enderger** [Frontrider/thaumic_arcana#3]
When self-enchantment is added into the mod, you could make it so that the incantation must be read by a golem.

**Comment by Frontrider** [comment]
I don't think a golem is suitable. They do not posses the required knowledge, and cognition to perform such acts. I've already went down the way of using an another substance to calm the mind, so that you can apply it to yourself.

**Comment by Frontrider** [comment]
The final method:
-you need to use an enchanting table (to channel the magic, and stabilize the process)
-you need to wear a gauntlet (to channel some vis from the aura to improve the stability of the process)
-you have to be under the effects of warp ward to calm yourself.
-the enchanted book of your choice.

**Comment by enderger** [comment]
Possibly for some enchantments bookshelves could be required

**Comment by Frontrider** [comment]
Yeah I'm thinking about that. The finalized methods:

- To get the book, you have to right click an enchanting table with a salis mundus in your main hand, and a book in your offhand (the book will spawn above the table)
- To get the enchanted books, you have to get a "formula" first, because  magic can not be applied the traditional way. The magical dust is the chosen medium, as it is semi-compatible.(Alchemy is too brutal for a whole animal, infusion is out of question) To get that:
  - you need to right click a special table, with a salis mundus, with a bottle of water.(you get a "stable mixture")
  - than you have to alcmemically (maybe use the altar as well?) infuse this mixture with the correct aspects to set the enchant.
 - To get the book:
  - you need to soak a base powder in this formula (sets the level of the enchant, currently there's 3 available)
  - than apply the dust to the prepared un-enchanted book, by right clicking an enchantment table with the dust, with the book in your offhand.
 - You can apply more, but more bookshelves will be required. bookshelf count increases depending on the number of existing enchantments.

You can also mix formulas, to reduce bookshelf count, but it will make the mixture unstable, which means that it can fail when you apply it.

The method change is what I'll need to reliably scale it, and be sure that this bug will not happen again. It also went through an internal rewrite, so now it's actually trivial to add more enchantments.

**Comment by Frontrider** [comment]
I'll call it done when I completely finished it.

**Comment by Frontrider** [comment]
I'm thinking about involving the brewing stand in this process, but I'm not sure.

**Comment by Frontrider** [comment]
![table](https://user-images.githubusercontent.com/6755034/43994275-b6b0162e-9d9a-11e8-84a1-311bc2b16329.gif)

**Comment by Frontrider** [comment]
And with that, I'm closing this issue as well. It scales,can be determined and craft-able up to level 2.
